"""Tests for qorm.codegen — model source generation."""

from __future__ import annotations

import ast
import textwrap

import pytest

from qorm.codegen import (
    _class_name,
    _QTYPE_TO_ALIAS,
    generate_model_source,
    generate_init_source,
)
from qorm.protocol.constants import QTypeCode


# ── _class_name ───────────────────────────────────────────────────────

class TestClassName:
    def test_simple(self):
        assert _class_name("trade") == "Trade"

    def test_underscored(self):
        assert _class_name("daily_price") == "DailyPrice"

    def test_multiple_underscores(self):
        assert _class_name("my_long_table_name") == "MyLongTableName"


# ── generate_model_source ─────────────────────────────────────────────

class TestGenerateModelSource:
    def test_basic_model(self):
        fields = [
            ("sym", QTypeCode.SYMBOL),
            ("price", QTypeCode.FLOAT),
            ("size", QTypeCode.LONG),
            ("time", QTypeCode.TIMESTAMP),
        ]
        source = generate_model_source("trade", fields)

        # Must be valid Python
        ast.parse(source)

        assert "class Trade(Model):" in source
        assert "__tablename__ = 'trade'" in source
        assert "sym: Symbol" in source
        assert "price: Float" in source
        assert "size: Long" in source
        assert "time: Timestamp" in source
        assert "from qorm import Model" in source
        assert "from qorm.types import" in source
        assert "Auto-generated by qorm" in source

    def test_keyed_model(self):
        fields = [
            ("sym", QTypeCode.SYMBOL),
            ("date", QTypeCode.DATE),
            ("close", QTypeCode.FLOAT),
            ("volume", QTypeCode.LONG),
        ]
        source = generate_model_source("daily_price", fields, key_fields=["sym", "date"])

        ast.parse(source)

        assert "class DailyPrice(KeyedModel):" in source
        assert "__tablename__ = 'daily_price'" in source
        assert "sym: Symbol = field(primary_key=True)" in source
        assert "date: Date = field(primary_key=True)" in source
        assert "close: Float" in source
        assert "volume: Long" in source
        assert "from qorm import KeyedModel" in source
        assert "from qorm import field" in source

    def test_all_type_aliases_covered(self):
        """Every column type in _QTYPE_TO_ALIAS should produce valid source."""
        for code, alias in _QTYPE_TO_ALIAS.items():
            fields = [("col", code)]
            source = generate_model_source("tbl", fields)
            ast.parse(source)
            assert f"col: {alias}" in source

    def test_mixed_list_column(self):
        fields = [
            ("sym", QTypeCode.SYMBOL),
            ("tags", QTypeCode.MIXED_LIST),
        ]
        source = generate_model_source("tagged", fields)
        ast.parse(source)
        assert "tags: List" in source

    def test_no_key_fields_means_model_base(self):
        source = generate_model_source("t", [("x", QTypeCode.LONG)])
        assert "class T(Model):" in source
        assert "KeyedModel" not in source

    def test_key_fields_means_keyed_model_base(self):
        source = generate_model_source("t", [("x", QTypeCode.LONG)], key_fields=["x"])
        assert "class T(KeyedModel):" in source

    def test_field_order_preserved(self):
        fields = [
            ("alpha", QTypeCode.SYMBOL),
            ("beta", QTypeCode.FLOAT),
            ("gamma", QTypeCode.LONG),
        ]
        source = generate_model_source("ordered", fields)
        lines = source.splitlines()
        field_lines = [l.strip() for l in lines if ": " in l and not l.strip().startswith("#")]
        # Exclude __tablename__ line
        field_lines = [l for l in field_lines if "__tablename__" not in l]
        assert field_lines[0].startswith("alpha:")
        assert field_lines[1].startswith("beta:")
        assert field_lines[2].startswith("gamma:")


# ── generate_init_source ──────────────────────────────────────────────

class TestGenerateInitSource:
    def test_single_model(self):
        source = generate_init_source([("trade", "trade")])
        ast.parse(source)
        assert "from .trade import Trade" in source

    def test_multiple_models(self):
        models = [
            ("fxtrades", "fxtrades"),
            ("daily_price", "daily_price"),
        ]
        source = generate_init_source(models)
        ast.parse(source)
        assert "from .fxtrades import Fxtrades" in source
        assert "from .daily_price import DailyPrice" in source

    def test_empty_list(self):
        source = generate_init_source([])
        ast.parse(source)
        assert "Auto-generated" in source


# ── CLI parser ────────────────────────────────────────────────────────

class TestCLI:
    def test_parser_host_port(self):
        from qorm.cli import _build_parser

        parser = _build_parser()
        args = parser.parse_args(["generate", "--host", "myhost", "--port", "5000", "--tables", "trade,quote"])
        assert args.command == "generate"
        assert args.host == "myhost"
        assert args.port == 5000
        assert args.tables == "trade,quote"
        assert args.output == "./models"

    def test_parser_service(self):
        from qorm.cli import _build_parser

        parser = _build_parser()
        args = parser.parse_args([
            "generate",
            "--service", "DS.CL.HDB.1",
            "--market", "fx",
            "--env", "prod",
            "--tables", "trade",
        ])
        assert args.service == "DS.CL.HDB.1"
        assert args.market == "fx"
        assert args.env == "prod"

    def test_parser_custom_output(self):
        from qorm.cli import _build_parser

        parser = _build_parser()
        args = parser.parse_args(["generate", "--host", "h", "--port", "1", "--tables", "t", "--output", "/tmp/out"])
        assert args.output == "/tmp/out"

    def test_main_no_command_returns_1(self):
        from qorm.cli import main

        assert main([]) == 1

    def test_main_generate_no_connection_returns_1(self, capsys):
        from qorm.cli import main

        ret = main(["generate", "--tables", "trade"])
        assert ret == 1
        captured = capsys.readouterr()
        assert "provide either --host/--port or --service" in captured.err

    def test_main_generate_service_missing_market(self, capsys):
        from qorm.cli import main

        ret = main(["generate", "--service", "A.B.C.D", "--tables", "trade"])
        assert ret == 1
        captured = capsys.readouterr()
        assert "--market and --env are required" in captured.err
